### ISSUE TITLE
Zoomed image appears pixelated/blurry

### ISSUE THREAD

**Issue by thurti** [vaheqelyan/svelte-zoom#12]
Sorry for spamming pull requests. This is the last one :)

This one is a little bit hard to reproduce. I only had this behavior on a low spec embedded device.
When you zoom in with pinch zoom the image appears blurry and kind of pixelated. This doesn't happen when using the manual zoom function.

I'm not an expert on this whole browser gpu rendering stuff. But to me it looks like the browser (in my case Chrome) doesn't update the GPU rendered representaiton of the image after zooming in. Instead it shows a scaled version of the initial (zoomed out) image.

I was able to fix this by dynamically adding and removing `will-change: transform` on `fireUp()` and `fireDown()`. This is also what is the recommended use of `will-change` according to [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change).

Let me know if anyone have more insights into this...

**Comment by vaheqelyan** [comment]
You are right, the `will-change` should be removed on `fireUp()`
When I was working on a project call l2w I wrote a hook called `useZoom`, This works more accurately (QA testing was included),,,,After that I decided to convert `useZoom` to `svelte-zoom`, and I forgot to bring some of my changes from react.js

**Comment by vaheqelyan** [comment]
i saved it
```js
const fireUp = useCallback(() => {
  matrix.current.x -= xY.current.newX;
  matrix.current.y -= xY.current.newY;

  scale.current.scaling = false;
  scale.current.lastHypo = 0;

  if (img.current) img.current.classList.remove(willChangeClassName);
}, [willChangeClassName]);

```
