### ISSUE TITLE
Must remove scroll event listeners on destroy

### ISSUE THREAD

**Issue by outerlook** [vaheqelyan/svelte-zoom#4]
Otherwise it will keep preventing scroll after navigating

**Comment by JakeCover** [comment]
Yep I have the same issue

**Comment by vaheqelyan** [comment]
This should solve the issue https://github.com/vaheqelyan/svelte-zoom/pull/5/commits/a3ec595c591f1467c62fc875ce4e96b2b37c6116

**Comment by JakeCover** [comment]
Ah, thank you!! Now if only the maintainer will come around to fix it...

**Comment by vaheqelyan** [comment]
try to install the latest version `1.0.13`
